# default: &default
#   adapter: postgresql
#   encoding: utf8
#   port: 5432
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#   username: username
#   password: password

# development:
#   <<: *default
#   database: safeway_development

# test:
#   <<: *default
#   database: safeway_test
