development:
  secret_key_base: c1eafb736a63e0c2a384054d32e6297a2142024d8dae3543458d68f2b19d5a63c48e750ee6c4dfd0ddf54106e0bfedbf87749a82d3c6b193158d7550d19f165c
  host: localhost:3000
  devise_mail: safeway@example.com
  default_mail: safeway@example.com
  digital_ocean:
    key_id: ''
    secret: ''
    region: ''
    bucket: ''
  geocoding_api_key: ''
  twilio_account_sid: ''
  twilio_auth_token: ''
  twilio_from_number: '+15005550006'
  redis_namespace: safeway
  redis_url: redis://127.0.0.1:6379/0
  data_usage_report_path: 'spec/support/data_usage_report.json'
  device_media_file:
    check_photo_status_after_n_sec: 25
    check_video_status_after_n_sec: 180
  mailer:
    sender_name: Example
    sender_email: example@exam.ple
test:
  secret_key_base: c1eafb736a63e0c2a384054d32e6297a2142024d8dae3543458d68f2b19d5a63c48e750ee6c4dfd0ddf54106e0bfedbf87749a82d3c6b193158d7550d19f165c
  host: localhost:3000
  devise_mail: safeway@example.com
  default_mail: safeway@example.com
  digital_ocean:
    key_id: ''
    secret: ''
    region: ''
    bucket: 'sternkraft'
  geocoding_api_key: ''
  redis_namespace: safeway
  redis_url: redis://127.0.0.1:6379/0
  data_usage_report_path: 'spec/support/data_usage_report.json'
  device_media_file:
    check_photo_status_after_n_sec: 25
    check_video_status_after_n_sec: 180
  mailer:
    sender_name: Example
    sender_email: example@exam.ple
production:
  secret_key_base: <%= ENV["SECRET_KEY"] %>
  devise_mail: <%= ENV["DEVISE_MAIL"] %>
  default_mail: <%= ENV["DEFAULT_MAIL"] %>
  host: <%= ENV["HOST"] %>
  digital_ocean:
    key_id: <%= ENV["DIGITAL_OCEAN_KEY_ID"] %>
    secret: <%= ENV["DIGITAL_OCEAN_SECRET"] %>
    region: <%= ENV["DIGITAL_OCEAN_REGION"] %>
    bucket: <%= ENV["DIGITAL_OCEAN_BUCKET"] %>
  geocoding_api_key: <%= ENV["GEOCODING_API_KEY"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_from_number: <%= ENV["TWILIO_FROM_NUMBER"] %>
  redis_namespace: <%= ENV["REDIS_NAMESPACE"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  mailer:
    sender_name: <%= ENV["MAILER_SENDER_NAME"] %>
    sender_email: <%= ENV["MAILER_SENDER_EMAIL"] %>
  smtp_host: <%= ENV["SMTP_HOST"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_domain:   <%= ENV["SMTP_DOMAIN"] %>
  smtp_authentication: <%= ENV["SMTP_AUTHENTICATION"] %>
  smtp_starttls_auto: <%= ENV["SMTP_STARTTLS_AUTO"] %>
  sentry_dsn: <%= ENV["SENTRY_DSN"] %>
  websocket_allowed_request_origins:
    - <%= ENV["CLIENT_HOST"] %>
    - !ruby/regexp '/\Ahttp:\/\/localhost:\d+/'
  data_usage_report_path: <%= ENV["DATA_USAGE_REPORT_PATH"] %>
  device_media_file:
    check_photo_status_after_n_sec: <%= ENV["DEVICE_MEDIA_FILE_CHECK_PHOTO_STATUS_AFTER_N_SEC"] %>
    check_video_status_after_n_sec: <%= ENV["DEVICE_MEDIA_FILE_CHECK_VIDEO_STATUS_AFTER_N_SEC"] %>

